### ISSUE TITLE
ALPINE_GLIBC_BASE_URL

### ISSUE THREAD

**Issue by AmritRaj23** [BWITS/Docker-builder#4]
Hey 

The link to the ALPINE_GLIBC_BASE_URL is not working. 

Thanks 
Amrit

**Comment by ozbillwang** [comment]
@AmritRaj23 
Seems the link is gone. Did you try with below package links?

https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.23-r3/glibc-bin-2.23-r3.apk

https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.23-r3/glibc-2.23-r3.apk

Let me know if this works or not? If works, you can raise PR.

**Comment by AmritRaj23** [comment]
@SydOps 

I tried running it but it does not find the ldconfig file in the /usr/glibc/usr/bin/ Any ideas? 

Here is the error: /usr/glibc/usr/bin/ldconfig: not found

The packages are installed. 

Thanks

**Comment by ozbillwang** [comment]
@AmritRaj23 

I made a new Dockerfile in branch `bugfix/#4`, please take a try.

**Comment by AmritRaj23** [comment]
@SydOps 

The installation of glibc is successful now.  

Thanks!
Amrit
