### ISSUE TITLE
Internal Error:  Your version of iconv does not support the "Mac Roman" encoding.

### ISSUE THREAD

**Issue by lacostenycoder** [BWITS/Docker-builder#5]
I am trying to use https://hub.docker.com/r/bwits/pdf2htmlex-alpine/
When I test this running
```
docker run -ti --rm -v ~/pdf/pdfdocker:/pdf  bwits/pdf2htmlex-alpine pdf2htmlEX --zoom 1.3 test.pdf
```
I get this error
```
Internal Error: Your version of iconv does not support the "Mac Roman" encoding.
If this causes problems, reconfigure --without-iconv.
Preprocessing: 4/4
Working: 4/4
```

I am running Docker on Mac OS 10.11.6  Not sure if this is where I should be posting this issue but any help is greatly appreciated.  Thanks.

**Comment by ozbillwang** [comment]
You can ignore this error message. you still get the converted file, right?

**Comment by lacostenycoder** [comment]
Thanks, it does appear to work.

**Comment by amit777** [comment]
Hi, i ran into the same issue. Sorry to comment on a closed thread. I'm just curious why this error message happens?  Does the PDF have Mac Roman encoding somehow?

**Comment by ghost** [comment]
不再更新了吗

**Comment by ozbillwang** [comment]
I didn't touch these docker images for more than 5 years.

Sure, let me take a look when have time and upgrade them if possible.
