### ISSUE TITLE
updated pdf2htmlEX/alpine/Dockerfile

### ISSUE THREAD

**Issue by NishealJ** [BWITS/Docker-builder#7]
Hi @darshandzend @ozbillwang can you update  pdf2htmlEX/alpine/Dockerfile to alpine 10?

**Comment by ozbillwang** [comment]
I don't have time to maintain it, if you want to, can raise a PR for it.

**Comment by NishealJ** [comment]
Hi, I tried but I'm stuck at 
<img width="586" alt="Screenshot 2020-06-06 at 5 00 07 PM" src="https://user-images.githubusercontent.com/41017303/83943554-bce59500-a81a-11ea-8e3d-a55e843c22c3.png"> do we need a gnu at alphine ? tho we don't have it in package manager

**Comment by ozbillwang** [comment]
it is very old tool, something has been changed a lot. 

even python2 has been removed from alpine latest package. So you have to fingure it out the reason by yourself now.

**Comment by NishealJ** [comment]
Thanks @ozbillwang for you kind reply. I'll check this.
